_target_: src.models.insect_pest_module.InsectPestLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

net:
  _target_: src.models.components.insect_pest_net.InsectPestClassifier
  input_size: 1280
  linear1_size: 1024
  linear2_size: 512
  linear3_size: 256
  output_size: 102
  dropout_size: 0.2
  freeze: true
